import { NavCard } from "@/components/NavCard/NavCard";
import Head from "next/head";
import Image from "next/image";
import mainbg from "../public/assets/images/mainbg.png";
import styles from "../styles/pages/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className={styles["heading-container"]}>
          <h1 className={styles.heading}>Hello, world!</h1>
        </div>
        <div className={styles.background}>
          <div className={styles.backgroundImage}>
            <Image
              src={mainbg}
              alt="main sitting at a desk, working on a laptop"
              fill
            />
          </div>
        </div>
      </div>
    </>
  );
}
